# ~/.tupperclaude.zsh — tupperclaude configuration
#
# This file is generated by `claude-docker-configure` from the template at
# zsh/templates/tupperclaude.zsh in the tupperclaude repo. It sets zstyle
# options that the plugin reads at *run* time (via `_claude_docker_opt`), so
# these lines take effect no matter where in .zshrc they are sourced from.
#
# Every option here also has an environment-variable fallback (see the
# comment above each block) and a hard default if neither is set. You do not
# need to touch this file by hand — re-run `claude-docker-configure` to
# regenerate it with different answers, or edit the zstyle lines directly if
# you know what you are changing.
#
# Run claude-docker-configure to regenerate.

# ---------------------------------------------------------------------------
# network — how the container reaches the internet
#
#   tailscale   a per-directory Tailscale sidecar container; the sandbox gets
#               full tailnet access under its own node identity (default)
#   default     plain Docker bridge networking, no sidecar, no Tailscale
#
# Env var: CLAUDE_DOCKER_NETWORK
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' network tailscale

# ---------------------------------------------------------------------------
# op-ref — 1Password secret reference for the Tailscale auth key
#
# Only consulted when TS_AUTHKEY is not already set in the environment (the
# env var always wins). Point it at a reusable, tagged Tailscale auth key:
#   https://login.tailscale.com/admin/settings/keys
#
# Unset by default — you must set either this or TS_AUTHKEY before the
# tailscale network mode will work.
#
# Env var: CLAUDE_DOCKER_OP_TS_REF
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' op-ref 'op://Private/Tailscale/authkey'

# ---------------------------------------------------------------------------
# aws — include the AWS CLI v2 in the built image
#
# Adds build time and image size, so it defaults to off. Takes effect on the
# next `claude-docker-build-arm` / `claude-docker-build-amd64`, not
# retroactively on an image already built.
#
# Env var: CLAUDE_DOCKER_INCLUDE_AWS
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' aws off

# ---------------------------------------------------------------------------
# home — host directory holding all tupperclaude state
#
# Per-instance teams/tasks/projects state, the Cargo cache, tmux/readline
# config, and the credentials file all live under this root. The playwright
# variant's state root is always this path with a -playwright suffix, so
# overriding `home` relocates both together.
#
# Default: ~/.config/claude-docker
#
# Env var: CLAUDE_DOCKER_HOME
# ---------------------------------------------------------------------------
# Unquoted, so the tilde actually expands. Quoted ('~/...') the value stays a
# literal '~' and the run path would mkdir -p a directory named '~' in $PWD.
# zstyle ':omz:plugins:tupperclaude' home ~/.config/claude-docker

# ---------------------------------------------------------------------------
# dockerfile — override the build recipe
#
# Almost never needed — the plugin already picks the right Dockerfile
# (docker/Dockerfile or docker/Dockerfile.playwright) for the variant you
# build. Set this only if you are maintaining a fork of the Dockerfile.
#
# Default: <repo>/docker/Dockerfile  (or Dockerfile.playwright)
#
# Give an absolute path. As with `home` above, a quoted '~/...' is NOT expanded
# — write ~/src/Dockerfile unquoted, or "$HOME/src/Dockerfile".
#
# Env var: CLAUDE_DOCKER_DOCKERFILE
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' dockerfile /path/to/Dockerfile
