# ~/.tupperclaude.zsh — tupperclaude configuration
#
# This file is generated by `claude-docker-configure` from the template at
# zsh/templates/tupperclaude.zsh in the tupperclaude repo. It sets zstyle
# options that the plugin reads at *run* time (via `_claude_docker_opt`), so
# these lines take effect no matter where in .zshrc they are sourced from.
#
# Every option here also has an environment-variable fallback (see the
# comment above each block) and a hard default if neither is set. You do not
# need to touch this file by hand — re-run `claude-docker-configure` to
# regenerate it with different answers, or edit the zstyle lines directly if
# you know what you are changing.
#
# Run claude-docker-configure to regenerate.

# ---------------------------------------------------------------------------
# network — how the container reaches the internet
#
#   tailscale   a per-directory Tailscale sidecar container; the sandbox gets
#               full tailnet access under its own node identity (default)
#   default     plain Docker bridge networking, no sidecar, no Tailscale
#
# Env var: CLAUDE_DOCKER_NETWORK
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' network tailscale

# ---------------------------------------------------------------------------
# op-ref — 1Password secret reference for the Tailscale auth key
#
# Only consulted when TS_AUTHKEY is not already set in the environment (the
# env var always wins). Point it at a reusable, tagged Tailscale auth key:
#   https://login.tailscale.com/admin/settings/keys
#
# Unset by default — you must set either this or TS_AUTHKEY before the
# tailscale network mode will work.
#
# Env var: CLAUDE_DOCKER_OP_TS_REF
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' op-ref 'op://Private/Tailscale/authkey'

# ---------------------------------------------------------------------------
# aws — include the AWS CLI v2 in the built image
#
# Also opens an `aws` tmux window with `aws sso login` pre-typed, ready for a
# single Enter when the lease expires.
#
# Adds build time and image size, so it defaults to off. Takes effect on the
# next `claude-docker-build-arm` / `claude-docker-build-amd64`, not
# retroactively on an image already built.
#
# Env var: CLAUDE_DOCKER_INCLUDE_AWS
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' aws off

# ---------------------------------------------------------------------------
# gcloud — include the Google Cloud SDK in the built image
#
# Also opens a `gcloud` tmux window with the ADC login pre-typed. With k8s on
# as well, the image additionally carries gke-gcloud-auth-plugin.
#
# Env var: CLAUDE_DOCKER_INCLUDE_GCLOUD
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' gcloud off

# ---------------------------------------------------------------------------
# k8s — include kubectl, helm and k9s in the built image
#
# Also opens a `k9s` tmux window running live against your current context, and
# mounts ~/.kube/config — that file alone, not the rest of ~/.kube. The copy
# inside the sandbox is writable, so logging into a different cluster in there
# leaves your host kubeconfig untouched.
#
# GKE clusters additionally need `gcloud` on: the auth plugin mints its tokens
# from the SDK.
#
# Env var: CLAUDE_DOCKER_INCLUDE_K8S
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' k8s off

# ---------------------------------------------------------------------------
# helm — which Helm major the k8s option installs
#
#   3      Helm 3 (default)
#   4      Helm 4
#   both   both, as `helm3` and `helm4`; bare `helm` is Helm 3
#
# Only changes the image when k8s is on, but the value is checked on every
# build: a typo is a typo whether or not helm is being installed. Both majors
# are maintained and charts written for 3 do not all render under 4, hence the
# choice.
#
# Under `both` the two share ~/.config/helm, ~/.cache/helm and
# ~/.local/share/helm: whichever runs first owns repository.yaml, and Helm 4 can
# rewrite it in a shape Helm 3 will not read. `helm3 repo update` rewrites it
# back; set HELM_CONFIG_HOME per major to keep them apart for good.
#
# Env var: CLAUDE_DOCKER_HELM
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' helm 3

# ---------------------------------------------------------------------------
# home — host directory holding all tupperclaude state
#
# Per-instance teams/tasks/projects state, the Cargo cache, tmux/readline
# config, and the credentials file all live under this root. The playwright
# variant's state root is always this path with a -playwright suffix, so
# overriding `home` relocates both together.
#
# Default: ~/.config/claude-docker
#
# Env var: CLAUDE_DOCKER_HOME
# ---------------------------------------------------------------------------
# Unquoted, so the tilde actually expands. Quoted ('~/...') the value stays a
# literal '~' and the run path would mkdir -p a directory named '~' in $PWD.
# zstyle ':omz:plugins:tupperclaude' home ~/.config/claude-docker

# ---------------------------------------------------------------------------
# machine-md — write MACHINE.md into the working directory at launch
#
# On launch the run path writes a MACHINE.md describing the sandbox to Claude
# (image, arch, variant, network mode, mounts, toolchain). It is rewritten
# whenever those differ from what the file records, so switching to the
# playwright variant does not leave Claude believing it has no browser — which
# also means your own edits to a tupperclaude-written MACHINE.md do not
# survive such a switch. A MACHINE.md this plugin did not write is never
# touched.
#
# Defaults to on. Turn it off if you would rather a first run did not modify
# whatever repository you happen to be standing in.
#
# Env var: CLAUDE_DOCKER_MACHINE_MD
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' machine-md on

# ---------------------------------------------------------------------------
# docker-sock — mount the host docker socket into the sandbox
#
# On (the default) lets Claude run `docker` inside the sandbox. It also means
# the sandbox is NOT a security boundary against the code running in it: the
# docker socket is equivalent to root on the host, so anything holding it can
# start a privileged container and read or write your whole filesystem.
#
# On by default because this tool is a reproducible, disposable ENVIRONMENT —
# its isolation is about not polluting the host, not about containing hostile
# code — and because MACHINE.md tells Claude that docker is available. Set it
# off for a real boundary, at the cost of docker-in-the-sandbox.
#
# Env var: CLAUDE_DOCKER_DOCKER_SOCK
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' docker-sock on

# ---------------------------------------------------------------------------
# dockerfile — override the build recipe
#
# Almost never needed — the plugin already picks the right Dockerfile
# (docker/Dockerfile or docker/Dockerfile.playwright) for the variant you
# build. Set this only if you are maintaining a fork of the Dockerfile.
#
# Default: <repo>/docker/Dockerfile  (or Dockerfile.playwright)
#
# Give an absolute path. As with `home` above, a quoted '~/...' is NOT expanded
# — write ~/src/Dockerfile unquoted, or "$HOME/src/Dockerfile".
#
# Env var: CLAUDE_DOCKER_DOCKERFILE
# ---------------------------------------------------------------------------
# zstyle ':omz:plugins:tupperclaude' dockerfile /path/to/Dockerfile
